### ISSUE TITLE
добавить ограничитель символов либо править верстку, чтоб не ломалось при длинном описании

### ISSUE THREAD

**Issue by VladyslavKovalchuk** [MalahVitalij/rocket-dokspb2#120]
http://prntscr.com/l23svc

**Comment by Derevyanchenko** [comment]
верстку поправил, не ломается
Но мне кажется нао ограничитель поставить( ибо убого выглядит с такой кучей )

**Comment by VladyslavKovalchuk** [comment]
добавить ограничитель, стр главная
